### ISSUE TITLE
Usar a API do Lucas Montano para pegar a quantidade de vaga de uma determinada área da TI

### ISSUE THREAD

**Issue by estevam5s** [Laboratorio-de-transformacao-Digital/job-tech-lab#4]

**Comment by ViniciusAndrade02** [comment]
OBS: Estevam já me passou o código
1-Rodar o script da minha maquina
2-Estudar Node
3-Puxar dados sobre a quantidade de vagas

**Comment by ViniciusAndrade02** [comment]
O node proibiu o Node de realizar um promise, basicamente,esse promise iria filtrar todos os resultados das vagas 

 let results = await Promise.allSettled(scrapingTasks);
